#%RAML 1.0
title: auropro-sample-proxy-withoutproxy
description: This RAML is designed to test without creating proxy API 

/sample:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {
                "message" : "success"
              }